services:
  postgres:
    image: postgres:16
    container_name: chorotega-postgres
    environment:
      POSTGRES_DB: chorotega_emarket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongodb:
    image: mongo:7
    container_name: chorotega-mongodb
    environment:
      MONGO_INITDB_DATABASE: chorotega_emarket
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./database/mongodb/seeds/seed-bitacora-pedidos.js:/docker-entrypoint-initdb.d/01-seed-bitacora-pedidos.js
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--eval",
          "quit(db.adminCommand('ping').ok ? 0 : 2)"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
  mongo_data: