name: CI - Chorotega E-Market

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  backend:
    name: Build Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/backend

    steps:
      - name: Obtener código del repositorio
        uses: actions/checkout@v6

      - name: Configurar Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: apps/backend/package-lock.json

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar linter
        run: npm run lint

      - name: Compilar backend
        run: npm run build

  frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/frontend

    steps:
      - name: Obtener código del repositorio
        uses: actions/checkout@v6

      - name: Configurar Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: apps/frontend/package-lock.json

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar linter
        run: npm run lint

      - name: Compilar frontend
        run: npm run build